version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    working_directory: ~/ultrasonic
    envoronment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: gradle-cache-{{ checksum "dependencies.gradle" }}
      - run:
          name: checkstyle
          command: ./gradlew -Pqc ktlintCheck
      - run:
          name: build
          command: ./gradlew assembleDebug
      - run:
          name: unit-tests
          command: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "dependencies.gradle" }}